// ...existing code where JSON is loaded...
jsonData = /* ... código que obtiene el JSON ... */;
// ...existing code...
// Agrega este log para confirmar el valor del JSON:
console.debug("DEBUG: Valor de 'participants' en JSON:", jsonData.data.participants);
// ...existing code que actualiza la caché...
cachedData.participants = jsonData.data.participants;
// ...existing code...
